"""create_syncs_runs_records_tables

Revision ID: ed00f753db49
Revises: 
Create Date: 2026-07-16 11:23:44.392831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed00f753db49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('adapter_id', sa.String(length=64), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_id', sa.String(length=255), nullable=True),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('high_water_mark', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncs_org_id'), 'syncs', ['org_id'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('source_uuid', sa.String(length=36), nullable=False),
    sa.Column('target_article_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_sync_records_sync_id'), 'sync_records', ['sync_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_count', sa.Integer(), nullable=True),
    sa.Column('removed_count', sa.Integer(), nullable=True),
    sa.Column('links_fixed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_sync_id'), 'sync_runs', ['sync_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_sync_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sync_records_sync_id'), table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_syncs_org_id'), table_name='syncs')
    op.drop_table('syncs')
    # ### end Alembic commands ###
